server:
  port: 8083

spring:
  application:
    name: ms-inventario
  datasource:
    url: jdbc:postgresql://localhost:5432/bodeganube_inventario
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
